#CONFIGURACIÓN METRICBEAT
metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - socket_summary
  enabled: true
  period: 10s
  processes: ['.*']

output.redis:
  hosts: ["localhost:6379"]
  password: "Jimena6721"
  key: "metricbeat"

# ======================= Elasticsearch template setting =======================

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

#  ssl:
#    enabled: true
#    verification_mode: none
