# Configuración Packetbeat

#=============================== Network device =============================
packetbeat.interfaces.device: any
packetbeat.interfaces.internal_networks:
  - private

# =================================== Flows =================================
packetbeat.flows:
  timeout: 30s
  period: 30s

# =========================== Transaction protocols =========================
packetbeat.protocols:
- type: icmp
  enabled: true
- type: amqp
  ports: [5672]
- type: dhcpv4
  ports: [67, 68]
- type: dns
  ports: [53]
- type: http
  ports: [80, 8080, 8000, 5000, 8002]
- type: nfs
  ports: [2049]
- type: tls
  ports:
    - 443   # HTTPS
    - 993   # IMAPS
    - 995   # POP3

# ================================== Outputs ===================================
output.redis:
  hosts: ["localhost:6379"]
  password: "Jimena6721"
  key: "packetbeat"
